apiVersion: v1
kind: ReplicationController
metadata:
  name: rctomcat
spec:
  replicas: 1
  selector:
    app: mytomcatserver
  template:
    metadata:
      name: tomcat
      labels:
        app: mytomcatserver
    spec:
      containers:
        - name: rctomcat
          image: middlewaredevops4/tomcatimagewithapp
          ports:
            - containerPort: 8080
