apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: tomcat
        image: middlewaredevops4/tomcatimagewithapp
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "1.0"
