apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
spec:
  containers:
  - name: tomcatpod
    image: middlewaredevops4/tomcatimagewithapp
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: tom2-secrets
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tom2-secrets
            key: password
