apiVersion: v1
kind: Pod
metadata:
  name: tomcatpodsec
spec:
  containers:
  - name: tomcatpodsec
    image: middlewaredevops4/tomcatimagewithapp
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: webserver-secrets
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: webserver-secrets
            key: password
